try {
    somefunction()
} catch (error) {
    console.log(error.message);
}

console.log('continue')